version: '3.5'
services:
  # Nginx反向代理服务

#  go-emby2alist: #emby反向代理服务，可以获取alist所挂载网盘的直链，默认关闭，如需使用可参考：https://github.com/AmbitiousJun/go-emby2openlist
#    image: crpi-zutrieltt9z6q9p7.cn-shanghai.personal.cr.aliyuncs.com/awordx/go-emby2alist:latest
#    environment:
#      - TZ=Asia/Shanghai
#      - GIN_MODE=release
#    container_name: go-emby2alist
#    volumes:
#      - /volume1/docker/alist_rename/config/config.yml:/app/config.yml
#    ports:
#      - 8895:8095 # http
#      - 8894:8094 # https

  # Alist文件重命名服务
  alist-rename:
    image: crpi-zutrieltt9z6q9p7.cn-shanghai.personal.cr.aliyuncs.com/awordx/open_alist_strm_rename:latest
    container_name: alist-rename
    ports:
      - "5050:5050"   # API服务端口
    volumes:
      - ./data:/usr/local/data                     #存放电影数据以及日志文件
      - ./config:/usr/local/config                 #存放配置文件
      - ./alist_strm:/alist_strm                   #右边alist_strm是容器内存放生成的strm文件
    restart: always

